// This file is generated by packages/design-tokens/scripts/generate.mjs.
// Do not edit it by hand; update packages/design-tokens/source.json instead.

type TokenValue = string | number;
type TokenTree = {
  [key: string]: TokenTree | TokenValue;
};

export const themes = {
  "default": {
    "color": {
      "bg": {
        "canvas": "#f4f1ea",
        "surface": "#fcfaf5",
        "elevated": "#fffdf8",
        "accentWash": "#d7ebe7",
        "inset": "#e9e3d8"
      },
      "border": {
        "subtle": "rgba(19, 32, 43, 0.12)",
        "strong": "rgba(19, 32, 43, 0.24)",
        "accent": "rgba(11, 92, 86, 0.32)"
      },
      "text": {
        "primary": "#13202b",
        "secondary": "#4b5b68",
        "muted": "#657482",
        "inverse": "#fffdf8"
      },
      "action": {
        "primary": "#0b5c56",
        "primaryHover": "#084a45",
        "secondary": "#efe9dc",
        "secondaryHover": "#e7dfcf"
      },
      "feedback": {
        "info": "#d6ece7",
        "infoText": "#0f5f59",
        "warning": "#f5e4bc",
        "warningText": "#7a4b06",
        "success": "#dcedde",
        "successText": "#1f5d35",
        "error": "#f8d6d2",
        "errorText": "#7c241b"
      },
      "focus": {
        "ring": "rgba(11, 92, 86, 0.28)"
      }
    },
    "font": {
      "family": {
        "display": "\"Space Grotesk\", \"IBM Plex Sans\", sans-serif",
        "ui": "\"IBM Plex Sans\", sans-serif",
        "mono": "\"IBM Plex Mono\", monospace"
      },
      "size": {
        "xs": "0.75rem",
        "sm": "0.875rem",
        "md": "1rem",
        "lg": "1.125rem",
        "xl": "1.5rem",
        "2xl": "2.375rem"
      }
    },
    "fontWeight": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700
    },
    "lineHeight": {
      "xs": 1.2,
      "sm": 1.35,
      "md": 1.5,
      "lg": 1.6,
      "xl": 1.1
    },
    "space": {
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem"
    },
    "radius": {
      "sm": "0.75rem",
      "md": "1.25rem",
      "lg": "1.75rem",
      "pill": "999px"
    },
    "shadow": {
      "card": "0 24px 60px rgba(19, 32, 43, 0.08)",
      "raised": "0 12px 32px rgba(19, 32, 43, 0.12)"
    },
    "motion": {
      "base": "180ms ease",
      "slow": "280ms ease"
    }
  }
} as const;

export const tokens = themes.default;

export const breakpoint = {
  "mobileMax": 767,
  "tabletMin": 768,
  "desktopMin": 1280
} as const;

const runtimeTokenTree = {
  ...tokens,
  breakpoint,
} as const satisfies TokenTree;

export type ThemeName = keyof typeof themes;
export type Tokens = typeof tokens;
export type Breakpoints = typeof breakpoint;

export type FlatTokenEntry = {
  cssVar: string;
  path: string;
  value: string;
};

function toCssSegment(segment: string) {
  return segment
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/\s+/g, "-")
    .toLowerCase();
}

function flattenTokenTree(
  tree: TokenTree,
  path: string[] = [],
): FlatTokenEntry[] {
  return Object.entries(tree).flatMap(([key, value]) => {
    const nextPath = [...path, key];

    if (typeof value === "string" || typeof value === "number") {
      return [
        {
          path: nextPath.join("."),
          cssVar: `--ds-${nextPath.map(toCssSegment).join("-")}`,
          value: String(value),
        },
      ];
    }

    return flattenTokenTree(value, nextPath);
  });
}

export const tokenEntries = flattenTokenTree(runtimeTokenTree);

export const flatTokens = Object.fromEntries(
  tokenEntries.map((entry) => [entry.path, entry.value]),
) as Record<string, string>;

export const tokensCss = [
  ":root {",
  ...tokenEntries.map((entry) => `  ${entry.cssVar}: ${entry.value};`),
  "}",
].join("\n");
