import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(packageRoot, "source.json");
const cssPath = path.join(packageRoot, "src", "tokens.css");
const jsonPath = path.join(packageRoot, "tokens.json");
const indexPath = path.join(packageRoot, "src", "index.ts");

/**
 * @typedef {string | number} TokenValue
 * @typedef {{ [key: string]: TokenTree | TokenValue }} TokenTree
 */

/**
 * @param {string} segment
 */
function toCssSegment(segment) {
  return segment
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/\s+/g, "-")
    .toLowerCase();
}

/**
 * @param {TokenTree} tree
 * @param {string[]} [pathParts]
 * @returns {{ path: string; cssVar: string; value: string }[]}
 */
function flattenTokenTree(tree, pathParts = []) {
  return Object.entries(tree).flatMap(([key, value]) => {
    const nextPath = [...pathParts, key];

    if (typeof value === "string" || typeof value === "number") {
      return [
        {
          path: nextPath.join("."),
          cssVar: `--ds-${nextPath.map(toCssSegment).join("-")}`,
          value: String(value),
        },
      ];
    }

    return flattenTokenTree(value, nextPath);
  });
}

const source = JSON.parse(await readFile(sourcePath, "utf8"));
const runtimeTokenTree = {
  ...source.themes.default,
  breakpoint: source.breakpoint,
};
const tokenEntries = flattenTokenTree(runtimeTokenTree);

const cssContents = [
  "/* This file is generated by packages/design-tokens/scripts/generate.mjs. */",
  ":root {",
  ...tokenEntries.map((entry) => `  ${entry.cssVar}: ${entry.value};`),
  "}",
  "",
].join("\n");

const flatTokens = Object.fromEntries(
  tokenEntries.map((entry) => [entry.path, entry.value]),
);

const indexContents = `// This file is generated by packages/design-tokens/scripts/generate.mjs.
// Do not edit it by hand; update packages/design-tokens/source.json instead.

type TokenValue = string | number;
type TokenTree = {
  [key: string]: TokenTree | TokenValue;
};

export const themes = ${JSON.stringify(source.themes, null, 2)} as const;

export const tokens = themes.default;

export const breakpoint = ${JSON.stringify(source.breakpoint, null, 2)} as const;

const runtimeTokenTree = {
  ...tokens,
  breakpoint,
} as const satisfies TokenTree;

export type ThemeName = keyof typeof themes;
export type Tokens = typeof tokens;
export type Breakpoints = typeof breakpoint;

export type FlatTokenEntry = {
  cssVar: string;
  path: string;
  value: string;
};

function toCssSegment(segment: string) {
  return segment
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/\\s+/g, "-")
    .toLowerCase();
}

function flattenTokenTree(
  tree: TokenTree,
  path: string[] = [],
): FlatTokenEntry[] {
  return Object.entries(tree).flatMap(([key, value]) => {
    const nextPath = [...path, key];

    if (typeof value === "string" || typeof value === "number") {
      return [
        {
          path: nextPath.join("."),
          cssVar: \`--ds-\${nextPath.map(toCssSegment).join("-")}\`,
          value: String(value),
        },
      ];
    }

    return flattenTokenTree(value, nextPath);
  });
}

export const tokenEntries = flattenTokenTree(runtimeTokenTree);

export const flatTokens = Object.fromEntries(
  tokenEntries.map((entry) => [entry.path, entry.value]),
) as Record<string, string>;

export const tokensCss = [
  ":root {",
  ...tokenEntries.map((entry) => \`  \${entry.cssVar}: \${entry.value};\`),
  "}",
].join("\\n");
`;

await mkdir(path.dirname(cssPath), { recursive: true });
await writeFile(cssPath, cssContents);
await writeFile(jsonPath, `${JSON.stringify(flatTokens, null, 2)}\n`);
await writeFile(indexPath, indexContents);
